#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors # Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  # colorscheme = "space-vim-dark"
  # colorscheme_bg = "dark"
  colorscheme = "onedark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

  autocomplete_method = "coc"
  snippet_engine = "ultisnips"

  automatic_update = true

  vim_help_language = "cn"

  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'

  windows_smartclose = ''
  escape_key_binding = ''

  # disabled_plugins = ['vim-node-rpc', 'jedi-vim']

  relativenumber = false

  # filemanager = "vimfiler"
  enable_vimfiler_gitstatus = false
  enable_vimfiler_welcome = false

  expand_tab = true
  statusline_unicode = false

  # enable_neomake = false
  # enable_ale = true

  # project_rooter_automatically = 0
  enable_cursorcolumn = true
  # disabled_plugins = ["neopairs"]
  todo_labels = ['FIXME', 'QUESTION', 'TODO', 'IDEA', 'fixme', 'question', 'todo', 'idea', 'comment']
  todo_prefix = '@'

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "chinese"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "default"

[[layers]]
  name = "leaderf"

[[layers]]
  name = "edit"

[[layers]]
  name = "git"
  git_plugin = 'fugitive'

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#python"
  enable_typeinfo = true


[[layers]]
  name = "lang#sh"

# [[layers]]
  # name = "lang#typescript"

[[layers]]
  name = "lang#vim"

# [[layers]]
  # name = "lang#vue"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "tools"

[[layers]]
  name = "todo"

[[layers]]
  name = "ui"
  enable_scrollbar=true

# ----------- stable -------------------
# vim 上一次打开的位置
[[custom_plugins]]
  repo = 'farmergreg/vim-lastplace'

# [[custom_plugins]]
  # repo = 'vim-scripts/LargeFile'

# doc: https://devhints.io/vim-easyalign
[[custom_plugins]]
  repo = 'junegunn/vim-easy-align'
  merged = false

# https://github.com/tpope/vim-speeddating
[[custom_plugins]]
  repo = 'tpope/vim-speeddating'

# https://github.com/vim-autoformat/vim-autoformat
[[custom_plugins]]
  repo = 'chiel92/vim-autoformat'

# https://github.com/wsdjeg/vim-todo
# [[custom_plugins]]
  # repo = 'wsdjeg/vim-todo'

# https://github.com/sillybun/vim-repl
[[custom_plugins]]
  repo = 'sillybun/vim-repl'
  on_ft = ['python']

# https://github.com/liuchengxu/vista.vim
[[custom_plugins]]
  repo = 'liuchengxu/vista.vim'

# [[custom_plugins]]
  # repo = 'numirias/semshi'

# [[custom_plugins]]
  # repo = 'sheerun/vim-polyglot'

# [[custom_plugins]]
  # repo = 'jceb/vim-orgmode'

# https://github.com/nvie/vim-togglemouse
[[custom_plugins]]
  repo = 'nvie/vim-togglemouse'

# [[custom_plugins]]
  # repo = 'jmcantrell/vim-diffchanges'

# https://github.com/mg979/vim-visual-multi
# [[custom_plugins]]
  # repo = 'mg979/vim-visual-multi'

# todo
# [[custom_plugins]]
  # repo = 'solarnz/thrift.vim'
  # on_ft = ['thrift']

# [[custom_plugins]]
  # repo = 'pseewald/vim-anyfold'
#
# [[custom_plugins]]
  # repo = 'tmhedberg/SimpylFold'

# https://github.com/axvr/org.vim
# [[custom_plugins]]
  # repo = 'axvr/org.vim'
  # on_ft = ['org']

# https://github.com/jiangmiao/auto-pairs
# [[custom_plugins]]
  # repo = 'jiangmiao/auto-pairs'

# [[custom_plugins]]
  # repo = 'lilydjwg/fcitx.vim'
  # branch = 'fcitx4'

# [[custom_plugins]]
  # repo = 'tommcdo/vim-fugitive-blame-ext'

# [[custom_plugins]]
  # repo = 'lfv89/vim-interestingwords'

# [[custom_plugins]]
  # name = 'tmhedberg/simpylfold'
  # on_ft = ['python']

# [[custom_plugins]]
  # repo = 'Konfekt/FastFold'
  # on_ft = ['json']

# [[custom_plugins]]
  # repo = 'kqito/vim-easy-replace'

# [[custom_plugins]]
  # repo = 'andrewferrier/vim-wrapping-softhard'

# [[custom_plugins]]
  # repo = 'mogelbrod/vim-jsonpath'
  # on_ft = ['json']


# [[custom_plugins]]
  # repo = 'wellle/context.vim'


# [[custom_plugins]]
  # repo = 'Yggdroot/indentLine'
  # on_ft = ['python', 'json', 'cpp']


# [[custom_plugins]]
  # repo = 'kkoomen/vim-doge'
  # on_ft = ['cpp', 'python']
  # build = ''

[[custom_plugins]]
  repo = 'hotoo/pangu.vim'

# [[custom_plugins]]
  # repo = 'skywind3000/vim-dict'

# [[custom_plugins]]
  # repo = 'github/copilot.vim'

# 如果使用 nvim，内部自建了 lsp
# [[layers]]
  # name = "lsp"
  # enabled_clients = ['vimls', 'clangd']

# ----------- test -------------------
[[custom_plugins]]
  repo = 'ryanoasis/vim-devicons'

[[custom_plugins]]
  repo = 'rhysd/accelerated-jk'

# [[custom_plugins]]
  # repo = 'ntpeters/vim-better-whitespace'

# [[custom_plugins]]
  # repo = 'gwilk/hive-syntax.vim'

# [[custom_plugins]]
  # repo = 'will133/vim-dirdiff'


# [[custom_plugins]]
  # repo = 'pseewald/vim-anyfold'

# [[custom_plugins]]
  # repo = 'wfxr/minimap.vim'

# [[custom_plugins]]
  # repo = 'tversteeg/registers.nvim'

# [[custom_plugins]]
  # repo = 'f-person/git-blame.nvim'

# [[custom_plugins]]
  # repo = 'karb94/neoscroll.nvim'

# [[custom_plugins]]
  # repo = 'mpyatishev/vim-sqlformat'

# [[custom_plugins]]
  # repo = 'folke/noice.nvim'

# [[custom_plugins]]
  # repo = 'nvim-lua/plenary.nvim'
# [[custom_plugins]]
  # repo = 'sindrets/diffview.nvim'

# [[custom_plugins]]
  # repo = 'shmup/vim-sql-syntax'
#
# [[custom_plugins]]
  # repo = 'nvim-orgmode/orgmode'
#
# [[custom_plugins]]
  # repo = 'rcarriga/nvim-notify'

[[custom_plugins]]
  repo = 'carbonscott/vim-smartfold'
  on_ft = ['config']

[[custom_plugins]]
  repo = 'pseewald/vim-anyfold'

[[custom_plugins]]
  repo = 'chiphogg/vim-prototxt'
